FROM python:3.11.15-alpine3.23
WORKDIR /app-streamlit
COPY streamlit_app.py requirements.txt /app-streamlit/
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]