FROM python:3.11.15-alpine3.23 AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11.15-alpine3.23 AS runner
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /usr/local/lib/python3.11/site-packages \
     /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin/uvicorn \
     /usr/local/bin/uvicorn
COPY main.py roast.py .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]