FROM python:3.11.15-alpine3.23 AS builder
WORKDIR /app
COPY  requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11.15-alpine3.23 AS runner
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin/streamlit \
     /usr/local/bin/streamlit
COPY streamlit_app.py .
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]